/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    BrandLogoAnimation: typeof import('./src/components/BrandLogoAnimation.vue')['default']
    FileDownload: typeof import('./src/components/FileDownload.vue')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
<<<<<<< HEAD
=======
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
>>>>>>> parent of 9837d46 (remove package and server)
    ISimpleIconsSupabase: typeof import('~icons/simple-icons/supabase')['default']
    ISimpleIconsVuedotjs: typeof import('~icons/simple-icons/vuedotjs')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerErrorAlert: typeof import('./src/components/ServerErrorAlert.vue')['default']
    StandardCard: typeof import('./src/components/StandardCard.vue')['default']
    TagLink: typeof import('./src/components/TagLink.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
    WhyUs: typeof import('./src/components/WhyUs.vue')['default']
  }
}
